# Generated by Django 5.2 on 2025-04-29 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Website', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='sold_out',
            field=models.BooleanField(default=False),
        ),
    ]
