# Generated by Django 5.2 on 2025-04-29 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Website', '0002_menuitem_sold_out'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('已送單', '已送單'), ('製作中', '製作中'), ('完成', '完成')], default='已送單', max_length=10),
        ),
    ]
