# Generated by Django 5.2 on 2025-04-30 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Website', '0003_order_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['created_at']},
        ),
        migrations.AddField(
            model_name='order',
            name='sequence_number',
            field=models.PositiveIntegerField(default=0, editable=False),
        ),
    ]
