# Generated by Django 5.2 on 2025-05-30 13:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Website', '0008_menu_menurating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menurating',
            name='menu_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='Website.menuitem'),
        ),
    ]
